### ISSUE TITLE
Create Producer Consumer for Data Retrieval in python with Kafka

### ISSUE THREAD

**Issue by bivasmaiti26** [airavata-courses/Blitzkrieg#1]
Create a producer microservice and a consumer microservice using Kafka

**Comment by virendrawali** [comment]
Setting up Kafka and creating producer and consumer.

**Comment by virendrawali** [comment]
Created data retrieval service which pushes data to kafka topic and another model executor service which is consuming data from kafka topic.

**Comment by virendrawali** [comment]
Added functionality for service registry, which helps microservice to register itself to zookeeper from which API gate will do service discovery.

**Comment by virendrawali** [comment]
Implemented.
