### ISSUE TITLE
Import issue in User Management

### ISSUE THREAD

**Issue by bivasmaiti26** [airavata-courses/Blitzkrieg#12]
There are several import issues in User Management, it doesn't find folders, This needs to be fixed.

**Comment by virendrawali** [comment]
Still issue is there, I tried running the the branch but getting same error.

**Comment by shindedarshan** [comment]
For the dependencies, today I will set up everything in a virtual environment. Once everything is running, I will freeze all packages so it will automatically generate requirements.txt file for all dependencies.

**Comment by shindedarshan** [comment]
Issue resolved by the code changes submitted by Bivas. All code changes have been merged to the user-management branch, so I think we are good to close this issue.
