### ISSUE TITLE
Merge all branches into a new branch and test it before merging it to master

### ISSUE THREAD

**Issue by shindedarshan** [airavata-courses/Blitzkrieg#13]

**Comment by virendrawali** [comment]
Had some issued about util function in userManagementController.py in function RegisterAPICall. So fixed it an pushed it into branch.

**Comment by virendrawali** [comment]
There was function call in componentdidmount which is not required right now. So removed function from function call.

**Comment by shindedarshan** [comment]
Merged all branches into the Master-beta branch.

**Comment by shindedarshan** [comment]
All testing has been done, hence marking this issue as close.
