### ISSUE TITLE
Create UserManagement

### ISSUE THREAD

**Issue by shindedarshan** [airavata-courses/Blitzkrieg#2]
Create user management to manage services like user registration, login, logout, etc.

**Comment by shindedarshan** [comment]
Currently, I have planned three services for user registration, login, and logout. Suggest me what else I should add in it.

**Comment by virendrawali** [comment]
Please use JWT with this to generate tokens which we can use in session management.

**Comment by shindedarshan** [comment]
Yes, a nice idea. I will use JWT to create tokens in my User model.
But that means I will have to add functionality to encode and decode JWT token. Again on logout, the token should invalidate. 
I will write the code then will send a pull request for code review and merging into the master branch.

**Comment by shindedarshan** [comment]
A new issue is created for Adding JWT functionality.
Issue title: "Add functionality to create JWT tokens to manage session"
Issue #: 4

**Comment by shindedarshan** [comment]
For the dependencies, today I will set up everything in a virtual environment. Once everything is running, I will freeze all packages so it will automatically generate requirements.txt file for all dependencies.

**Comment by shindedarshan** [comment]
All functionalities have been implemented, tested and integrated with other components. The objective of this task has been completed. Hence, closing this issue.
