### ISSUE TITLE
Unable to find node in zookeeper error

### ISSUE THREAD

**Issue by nmnayak** [airavata-courses/Blitzkrieg#23]

**Comment by shindedarshan** [comment]
This issue only occurs when all microservices have not registered with zookeeper. If no instance of any microservice is currently up and running (with registered itself with zookeeper), then only this issue occurs. 
In your case, you might have forgot to start any one of the microservice, hence you were facing this issue. So, this is not a valid bug and hence marking it as closed with the invalid label.
