### ISSUE TITLE
Create Session Management 

### ISSUE THREAD

**Issue by bivasmaiti26** [airavata-courses/Blitzkrieg#3]
Create a Session Management Microservice in Java to store and track user activity

**Comment by bivasmaiti26** [comment]
Creating Session Management Project

**Comment by bivasmaiti26** [comment]
Created Collections in Atlas, will use Mongo DB for session management

**Comment by bivasmaiti26** [comment]
Need to finalize the Session object class, I have added userName, requestName, requestStatus and requestTime. @shindedarshan please suggest if anything else is needed?

**Comment by bivasmaiti26** [comment]
Committed spring boot application in branch session-management.

**Comment by shindedarshan** [comment]
I think the variables you have discussed earlier is enough.

**Comment by bivasmaiti26** [comment]
The application is implemented in Spring Boot
