### ISSUE TITLE
Develop jenkins pipeline for continuous integration

### ISSUE THREAD

**Issue by virendrawali** [airavata-courses/Blitzkrieg#35]

**Comment by shindedarshan** [comment]
Created 4 different Jenkins pipelines for user-management, weather services, API gateway, and UI.
Written Jenkinsfile for each of these pipelines and committed to the GitHub repository.
Added sparse path setting for each pipeline, so it will create the build of that particular microservice which has changed.
This task has been completed. Hence, marking it as close.
