### ISSUE TITLE
Add functionality to create JWT tokens to manage sessions

### ISSUE THREAD

**Issue by shindedarshan** [airavata-courses/Blitzkrieg#4]
JWT can be used to create auth tokens which will help to manage sessions. We will have to write some functions to create JWT token for the user while login and to verify the token while every subsequent request to validate session and valid active user.
This will add extra responsibility for writing unit tests to test all possible scenarios.

**Comment by shindedarshan** [comment]
Implemented JWT token in the User model. Added functionalities for generating the auth token and validating the auth token. But I think validate_token functionality should move out of the user_management component and add it to the session_management component. Because once a user is login and received JWT token, a session is started. Then session_management component should be responsible for validating every subsequent request.

**Comment by bivasmaiti26** [comment]
JWT Token validation is being done in Session management.Invalid token are being saved in database and referred to while token validation. Closing this issue
