### ISSUE TITLE
database connection failure in user management

### ISSUE THREAD

**Issue by virendrawali** [airavata-courses/Blitzkrieg#41]

**Comment by shindedarshan** [comment]
Postgres database is hosted on some another Jetstream instance for persistent data storage. But user-management microservice was trying to connect the Postgres database on the localhost. Hence it was throwing error.

The host and port for Postgres database connection which is provided in config.py file has been changed to appropriate values. This change has fixed this issue.

**Comment by shindedarshan** [comment]
Assigning @virendrawali as a reviewer for code review.

**Comment by virendrawali** [comment]
looks good!
