### ISSUE TITLE
CD pipeline is not set up

### ISSUE THREAD

**Issue by DishaTalreja3** [airavata-courses/Blitzkrieg#54]

**Comment by bivasmaiti26** [comment]
Hi Disha, 
CD Pipeline is now set up. Please make some changes in the UI, CI/CD pipeline will trigger based on that.  One place you can change the UI is the UI/src/Header.js file .
You should be able to see your changes reflect in the UI after several minutes. 
You can also check docker hub repository thertion12 to check the latest images being pushed.

**Please make all changes in the dockerize-project-test branch.**
