### ISSUE TITLE
Unable to find Kubernetes deployment files

### ISSUE THREAD

**Issue by adithyaselv** [airavata-courses/Blitzkrieg#55]

**Comment by bivasmaiti26** [comment]
Please go to dockerize-project-test branch, you will find deployment.yml file under /UI folder

**Comment by adithyaselv** [comment]
Thanks I see it was added here - https://github.com/airavata-courses/Blitzkrieg/commit/57161b29f0e25b80ad719ea9466304e945c27dd4
