### ISSUE TITLE
Wiki has not been setup

### ISSUE THREAD

**Issue by akshaygpt** [airavata-courses/Blitzkrieg#56]
Not able to proceed with the review without wiki.

**Comment by shindedarshan** [comment]
This is the duplicate issue of #53. Hence, keeping #53 open and closing this issue by marking as duplicate.

**Comment by bivasmaiti26** [comment]
Hi Akshay, we are currently in the process of updating the wiki. PFB some of the information to get you started on the review process:
1. The application is hosted at [(http://149.165.170.68:30007)]
2. The branch to review the project is dockerize-project-test
3.  CI/CD pipeline is setup, you can check by making a small change in the  UI.  One place you can change the UI is the UI/src/Header.js file .
4. You should be able to see your changes reflect in the UI after several minutes.
5. You can also check docker hub repository thertion12 to check the latest images being pushed.

**Comment by akshaygpt** [comment]
Closing this for duplication.
