### ISSUE TITLE
created jenkinsfile for weather data

### ISSUE THREAD

**Issue by virendrawali** [airavata-courses/Blitzkrieg#58]

**Comment by shindedarshan** [comment]
Created Jenkinsfile for wather-services microservices.
Added stages for clone the source code from GitHub repo, generate docker image, push docker image on docker hub, deploy container image in Kubernetes.
Tagged this Jenkinsfile with respective Jenkins pipeline.

**Comment by shindedarshan** [comment]
This task has been completed, hence marking it as close.
