### ISSUE TITLE
Debugger not removed from the code

### ISSUE THREAD

**Issue by akshaygpt** [airavata-courses/Blitzkrieg#64]
When I access the app from the UI, on typing a location, the UI pauses because of a debugger.

![blitz1](https://user-images.githubusercontent.com/15238105/77218272-f94d0300-6aff-11ea-8303-66abf8be4115.PNG)

**Comment by shindedarshan** [comment]
Removed debugger as well as some unwanted console.log lines from the code.

**Comment by shindedarshan** [comment]
You can check it again and close the issue.

**Comment by akshaygpt** [comment]
I just checked again, it's still there.

**Comment by akshaygpt** [comment]
It's in `sendCityData` function

**Comment by shindedarshan** [comment]
This issue has been resolved by the code changes provided in commit #95472fd

**Comment by shindedarshan** [comment]
This issue no more exists after the provided code changes, hence closing this issue.
