### ISSUE TITLE
Setup Load Balancing with Canary in Kubernetes Cluster

### ISSUE THREAD

**Issue by bivasmaiti26** [airavata-courses/Blitzkrieg#70]
Please setup Load Balancing between master and slave VMs with Canary

**Comment by shindedarshan** [comment]
Deployment source code related to the load-balancer and canary deployment has been pushed in the deployment directory. 
Apply these deployment files in Kubernetes.

**Comment by shindedarshan** [comment]
By performing the above steps load balancer and canary deployment will be configured. This task has been completed. Hence, marking it as close.
